#! /bin/sh
sxhkd &
(wal -R)
sh ~/.screenlayout/auto.sh

if  xrandr | grep "VGA-1 connected"; then
    bspc monitor VGA-1 -d 1 2 3 4
    bspc monitor LVDS-1 -d 5 6 7 8
else
    bspc monitor -d 1 2 3 4 5 6 7 8
fi

compton &
sh ~/bin/misc/launch_dunst.sh

#
## config
#


# colors
bspc config active_border_color   $color8
bspc config normal_border_color   $color8
bspc config focused_border_color  $foreground
bspc config presel_feedback_color $color1

# border
bspc config border_width         0

# gaps and padding
bspc config window_gap         5 
bspc config top_padding        5 
bspc config right_padding      5 
bspc config bottom_padding     5 
bspc config left_padding       5 

bspc config split_ratio          0.5

bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true

# rules
bspc rule -a Zathura state=tiled #for whatever reason zathura starts floating by default

sh ~/.config/polybar/launch.sh
nitrogen --restore &
~/.conky/launch_all.sh
xset r rate 300 60
xinput set-prop 12 288 1

sh ./autostart.sh
